### ISSUE TITLE
Does prompt close stdin?

### ISSUE THREAD

**Issue by yegodz** [flatiron/prompt#105]
Hi..
I am calling prompt inside of a function that is being called from within the `eval` function of a node REPL (created using `repl = require('repl').start(...)`.

The node REPL always exits with code 0 as soon as the `prompt.get()` returns

I managed to fix this by resetting `repl.rli.input = process.openStdin();` right before returning from `prompt`

Is this the expected behavior? Is `prompt` closing out the input stream `process.stdin`?

**Comment by gangstead** [comment]
I'm sorry no one got you an answer in the last year, but it sounds like you have a work around.  I'm trying to close out inactive issues, if this is a lingering problem add some more info and reopen.
