### ISSUE TITLE
Add choices

### ISSUE THREAD

**Issue by gobwas** [flatiron/prompt#111]
Does it able to add choices in prompt?
For example, enum field in json-schema?

**Comment by senthilporunan** [comment]
+1 .. is there any workaround for this ?

**Comment by senthilporunan** [comment]
@gobwas It is working if we add like this "enum": [ "CANCELLED", "COMPLETED"]

**Comment by gangstead** [comment]
Not sure what the problem is here.  I'm trying to close out inactive issues.  If you can add more clarity we please reopen.
