### ISSUE TITLE
Start node server with properties?

### ISSUE THREAD

**Issue by colesimmons** [flatiron/prompt#125]
Is there a way to start a node server with the properties that prompt is going to request? Something like `node server.js my_username my_password`? Occasionally I would like to start the server via child_process.fork, but this doesn't seem to be possible with prompt.

**Comment by gangstead** [comment]
Command line args are not in the scope of this module.  Sounds like you need to bring in something like https://github.com/tj/commander.js to bring in command line parameters.  On my projects I end up using both.  I read the parameters into a commander variable called `program`  and setting the default value of the prompt to `program.myfield`

**Comment by colesimmons** [comment]
@gangstead :+1: thank you!
