### ISSUE TITLE
Not registering the second option in prompt.get([optiion1,option2])....etc

### ISSUE THREAD

**Issue by jdalrymple** [flatiron/prompt#131]
Allows me to enter in the first option value, but once i click enter to move to the following option2, it just returns, showing the second option as a blank value.  I added three options and it still skipped the second one and worked find for the third which is also odd.

I used this code to test:
```javascript
var prompt = require('prompt');

  //
  // Start the prompt
  //
  prompt.start();

  //
  // Get two properties from the user: username and email
  //
  prompt.get(['username', 'email'], function (err, result) {
    //
    // Log the results.
    //
    console.log('Command-line input received:');
    console.log('  username: ' + result.username);
    console.log('  email: ' + result.email);
  });
```

**Comment by mikeRead** [comment]
Im having the same problem,Admins should probably merge my issue #132 into this as it looks to be the same thing... sorry I tried searching but didn't see this until I was looking at my issue again today.

I "fixed" it by doing something like this by adding the second parameter as "bug"  
(didn't test this example)
```javascript
 prompt.get(['username', 'bug', 'email'], function (err, result) {
    //
    // Log the results.
    //
    console.log('Command-line input received:');
    console.log('  username: ' + result.username);
    console.log(' ignore: ' + result.bug);
    console.log('  email: ' + result.email);
  });
```

**Comment by jdalrymple** [comment]
Noticed on one of my other computers using an older version of node, the problem doesn't exist. Im going to upgrade and see if it returns.

**Comment by jdalrymple** [comment]
Tested with linux  node version 4.2.1 Also works fine. @mikeRead are you running it on windows?

**Comment by mikeRead** [comment]
Thanks, I am running on windows using node v4.1.1

**Comment by jdalrymple** [comment]
I test on windows with node v4.2.1 and the bug happened.

**Comment by jonathansampson** [comment]
I also appear to be hitting this bug on Windows 10, running Node 4.2.1.

**Comment by CameronK** [comment]
This bug has something to do with the way the prompt is initialized - it only occurs after the first input.

```
var promptSchema = {
	properties: {
		"Mission name": {
			pattern: /^[a-zA-Z\s\-]+$/,
			message: 'Name must be only letters, spaces, or dashes',
			required: true
		},
		"Skip this prompt": {

		},
		"Admin username": {
			required: true
		}, 
		"Admin PIN": {
			required: true
		}
	}
};
```

Running prompt with this schema and entering invalid input into the first prompt ("Mission name") causes the error message to pop up, then immediately pop up again (because the program outputs the error but also receives it as input, which is invalid based on that pattern). Entering correct input afterwards and you get through all four prompts.

**Comment by mikeRead** [comment]
Its a bit off topic but you probably need to use  description if you keys have space in them
```javascript
...
//remove space
"Mission_name": {
            //add description
            description:"Mission name",
            pattern: /^[a-zA-Z\s\-]+$/,
            message: 'Name must be only letters, spaces, or dashes',
            required: true
        }, 
...
```

**Comment by CameronK** [comment]
Hmm. I ran node using the "Git Bash" program that comes shipped with Github's Windows desktop program and the bug seems to be gone.

**Comment by mikeRead** [comment]
I'm not sure exactly what you mean but running ``` npm install https://github.com/flatiron/prompt.git --save ``` didn't work for me in my project it should be the exact same code? what version of node are you using?

**Comment by CameronK** [comment]
I'm talking about the command prompt window. If you install Github for Windows, you also receive "Git Bash" which a port of the Linux-style environment/command-line tools.

Node version 4.2.1

**Comment by nickdbush** [comment]
On all of my command prompts this error happens. Especially annoying when trying to type in passwords! Command Prompt, PowerShell, Git and CMDer all display this bug. Any ETA on this being fixed?

Running Windows 10 64bit with Node 5.0.0

**Comment by cdoole** [comment]
I'm also using windows 10 64bit but i have Node 4.2.2. I'm working on a project for a course and it keeps skipping the second parameter

**Comment by masiorama** [comment]
Windows 10 64bit but i have Node 4.2.2, same problem here.

**Comment by gregwilton** [comment]
Upgrading to Node 5.3.0 fixed this for me. Was previously getting this error on Node 4.0.0 on Win 10.

**Comment by Cellule** [comment]
I had the same issue, I upgraded from Node 4.1.2 => 5.5.0 and the bug is gone.

**Comment by jcrugzz** [comment]
still an issue with node@4.2.6?

**Comment by gangstead** [comment]
Not sure if/how to resolve this one.  It sounds like some magic in Node 5 fixes it, but I don't have a Windows machine to verify that it works or not on any version of Node.  Anybody still having the problem on Node 5?

**Comment by gangstead** [comment]
I'm going to go ahead and close since we have a fix (Windows users upgrade to Node 5).  It doesn't give me warm feelings that the root cause wasn't found, but at least we have an answer for anyone else with the problem.  We can always reopen to keep the discussion going if anyone disagrees.

**Comment by caub** [comment]
@edupoly or https://www.npmjs.com/package/prompt-ajv for a light and simple alternative
