### ISSUE TITLE
Request to add new admin

### ISSUE THREAD

**Issue by gangstead** [flatiron/prompt#138]
Hey Flatiron crew: @indexzero @3rd-Eden @bmeck @dscape @jcrugzz @Swaagie 

It looks like the current admins don't have the time to give this repo the love it needs.  I don't see any activity for at least 9 months and things like CI build are broken.  Would yall be willing to let another person on as admin to help keep things up to date?

I'm happy to have anyone do it, but I also volunteer if no one else comes to mind.

**Comment by indexzero** [comment]
Yes.

**Comment by indexzero** [comment]
@gangstead the first place is issue triage. Could you do a pass over issues and then close out the issues that should be closed or @ summon me appropriately?

**Comment by gangstead** [comment]
Great.  Looks like I need admin (or create a new group in the org with the privileges you'd like to give me) for this repo in order to close out the dead issues.

**Comment by indexzero** [comment]
Done. You are now an admin. Let me know where you end up :+1:
