### ISSUE TITLE
Need minor release on npm

### ISSUE THREAD

**Issue by gangstead** [flatiron/prompt#144]
I've merged 8 pull requests in the last couple days fixing some bugs and adding some features.  No breaking changes so I think it's time for a minor release.

@indexzero @jcrugzz @indutny 
You three are the owners of the npm package.  Can one of you either add me as an owner:
```
> npm owner add gangstead
```
Or do a minor release:
```
> git pull
> npm version minor
> npm publish
> git push
```

Please and thank you.

**Comment by jcrugzz** [comment]
`v0.3.0` was published. Thanks for the good work!
