### ISSUE TITLE
Need major release on npm

### ISSUE THREAD

**Issue by gangstead** [flatiron/prompt#149]
In updating dependencies we lost the so-called "unsafe" `colors` module that adds colors to the String prototype #146 .  We now use `colors/safe` in the project, readme, and example.

Since this is a breaking change for anyone using colors it needs to go into a major release.  Can one of the npm maintainers @indexzero @jcrugzz @indutny please do a `git pull && npm publish`?  

I've already updated the package version to `1.0.0` so there is no need to do an `npm version major`

**Comment by indexzero** [comment]
@gangstead done and done! Thanks for your hard work so far. What's next on your agenda?
