### ISSUE TITLE
false value ignored when using argv fallback

### ISSUE THREAD

**Issue by schalkneethling** [flatiron/prompt#151]
First of, thanks for a great lib! However ;) I might have uncovered a bug or two.

It seems that, when using `prompt.override = argv;` (`argv` === yargs[1]) where the value returned for the argument is `false`, it is ignored by `prompt` and the user is prompted instead of simply using the value provided by `argv`

For example:

```
var copySchema = {
        properties: {
            ...
            clobber: {
                description: 'Do you wish to overwrite existing files or directories?',
                type: 'boolean',
                default: false
            },
            preserveTimestamps: {
                description: 'Preserve source file/folder(s) timestamps?',
                type: 'boolean',
                default: false
            }
        }
    };
```

yargs is configured as follows:

```
var argv = yargs.boolean(['clobber','preserveTimestamps']).argv;
```

So, when the arguments are present on the command line, logging `prompt.override` returns:

```
{ _: [],
  clobber: true,
  preserveTimestamps: true,
  task: 'copy',
  filesFolders: 'node_modules,lib',
  destination: 'dist',
  '$0': 'fsys' }
```

Also, the function completes without issuing any prompts. When the arguments are not present however, logging `prompt.override` returns:

```
{ _: [],
  clobber: false,
  preserveTimestamps: false,
  task: 'copy',
  filesFolders: 'node_modules,lib',
  destination: 'dist',
  '$0': 'fsys' }
```

So, even though clobber and preserveTimestamps are set to false, prompt does not read these, and continues to prompt the user for input.

I see two problems here:
1) Clearly prompt should have used the false values set in argv [bug?]
2) Even if there is no value provided for these two arguments, should prompt not use the default and not prompt the user?

[1] https://github.com/yargs/yargs

**Comment by blahah** [comment]
In general any `override` value that is false is ignored. This is because [the test for whether an override exists[(https://github.com/flatiron/prompt/blob/master/lib/prompt.js#L468) is a truthiness test - it should test for the property on the `overrides` object.

PR incoming.
