### ISSUE TITLE
How to continuously prompt

### ISSUE THREAD

**Issue by kahunacohen** [flatiron/prompt#165]
How would I continuously prompt until a user say hit a certain key? For example let's say I have an array of items to pass to `prompt.get`, but I want to keep prompting until a user hits, say "q". How to do that? I tried putting it all in a while loop, but the prompt doesn't wait. I assume this has to do with node's asynchronous nature...

**Comment by adambuczynski** [comment]
You can solve this using a recursive function that awaits a prompt and then when received, processes it and then starts awaiting the prompt again.

Here's some code of my solution, but note that I have promisified the `prompt.get` method using the Bluebird promise library.

```js
const prompt = require('prompt');
const Promise = require('bluebird');

prompt.get = Promise.promisify(prompt.get);
prompt.message = '';
prompt.delimiter = '';

/**
 * Await command
 */
function awaitCommand() {

  //Start prompt
  prompt.start();
  return prompt.get({
    name: 'command',
    description: 'Enter command:',
  })
    .then(result => result.command)
    .then(command => {
      //Do stuff
    })
    .catch(error => {

      //Prompt cancelled, exit process
      if (error.message === 'canceled') {
        system.exit();
      }

      //Log error
      console.log(chalk.yellow(error.message));
    })
    .then(awaitCommand); //<-- wait for next prompt
}

//Start prompt
awaitCommand();
```

**Comment by Chippd** [comment]
Thanks for this, using your @adamreisnz I was able to make my own version without Bluebird.
``` 
import prompt from 'prompt';

function startPrompt() {
	prompt.start();

	prompt.get(["WLID"], async function (err, result) {
		if (err) { return onErr(startPrompt); }
		
		// Do stuff
		
		console.log('Done!');

		startPrompt()
	});
}

startPrompt()
```

**Comment by caub** [comment]
prompt.get support promise now by default, so you could write:

```js
while (yourCondition) {
  const { wlid } = await prompt.get({ properties: { wlid: { description: 'Some id', required: true } } });

  // update yourCondition
}
```
