### ISSUE TITLE
Add promise version of ".get(...)" function

### ISSUE THREAD

**Issue by ujeenator** [flatiron/prompt#176]
It's expected to work like this:
```
async function main() {
    const {userName, email} = await prompt.getAsync(['username', 'email'])
    console.log('  username: ' + username);
    console.log('  email: ' + email);
}
```

Or like this (without async/await):
```
prompt.getAsync(['username', 'email'])
    .then(result => {
       console.log('Command-line input received:');
       console.log('  username: ' + result.username);
       console.log('  email: ' + result.email);
    }).catch(err => {
      // ...
    })
```

It cat be easily implemented with node-promisify wrapper (I already test it):
```
var promisify = require('node-promisify')

prompt.getAsync = promisify(prompt.get)
```

**Comment by BridgeAR** [comment]
I would be willing to open a PR for this but I'm not certain if this would be [accepted](https://github.com/flatiron/prompt/issues/81#issuecomment-74585483).

Are you open for a PR for this? I guess things changed over time and most people use async await or promises by now.

**Comment by Vac1911** [comment]
not a maintainer but this added in [PR 196](https://github.com/flatiron/prompt/pull/196)

**Comment by caub** [comment]
Yes, prompt.get is now promisified out of the box, let's close, thanks guys
