### ISSUE TITLE
bug: giving default a function returns the stringified version of the function

### ISSUE THREAD

**Issue by 3stacks** [flatiron/prompt#178]
```
prompt.get([
  {
    name: 'themeName'
  },
  {
    name: 'themeSlug',
    default: function() {
      return 'foo';
    },
    pattern: /^[a-z]+(-[a-z]+)*$/gm
  }
], (err, result) => {...})
```

The default value of the themeSlug prompt is `function() {
      return 'foo';
    }` as a string.

EDIT: I just installed the package by pointing to the git repo and it's working correctly.

Was this feature not added as of ^1.0.0 which I am currently on? (installed from npm without explicitly adding version)

**Comment by AckerApple** [comment]
Thank you for reporting this issue as it saved me time.

Yes and confirmed, do not use npm version if default function needed.

```
npm install github:flatiron/prompt
```

**Comment by caub** [comment]
why isn't npm package up to date?

**Comment by 3stacks** [comment]
Closing this issue because it most likely won't be addressed! I've switched to enquirer (https://www.npmjs.com/package/enquirer)
