### ISSUE TITLE
.then is Not a Function 

### ISSUE THREAD

**Issue by arb** [flatiron/prompt#200]
Per the [documentation](https://github.com/flatiron/prompt#usage), if I omit a callback to `.get` then prompt should return a `Promise`. However, will the code below, I receive an error.

```js
const Prompt = require('prompt');
Prompt.start();
Prompt.get(['name']).then(console.log);
```

The error is:
```
Prompt.get(['name']).then(console.log);
                     ^

TypeError: Prompt.get(...).then is not a function
```

Looking through the source code of prompt, I don't see anything for creating or returning promises. What am I missing?

Prompt version: `1.0.0`
Node version: `10.19.0`

**Comment by caub** [comment]
fixed in 1.2.0

thanks for reporting
