### ISSUE TITLE
Move off abandoned utile dependency

### ISSUE THREAD

**Issue by mriedem** [flatiron/prompt#213]
`utile` was last updated in 2014 [1] and has an open security vulnerability issue reported against it [2] but it's pretty clearly abandoned [3].

It looks like `utile` is only used here:

https://github.com/flatiron/prompt/blob/c071b85b9a28e3fb561d53d1d541469c8fe6ec1e/lib/prompt.js#L321

and here:

https://github.com/flatiron/prompt/blob/c071b85b9a28e3fb561d53d1d541469c8fe6ec1e/lib/prompt.js#L412

Maybe the [async](https://www.npmjs.com/package/async) library could be used instead which has similar functionality and is actively maintained:

https://caolan.github.io/async/v3/docs.html#eachOfSeries

https://caolan.github.io/async/v3/docs.html#rejectSeries

[1] https://github.com/flatiron/utile/releases
[2] https://github.com/flatiron/utile/issues/28
[3] https://github.com/flatiron/utile/commits/master

**Comment by caub** [comment]
Good point, and for `utile.mixin`, what could we do? I think it's like `Object.assign`, but since this package tries to support node 0.6+, we could have a loop

Do you think you could try a quick MR with your replacement utile -> async?
