### ISSUE TITLE
URGENT!!!! colos 1.4.x is broken! YOur dependency will get this version!

### ISSUE THREAD

**Issue by Apollon77** [flatiron/prompt#220]
Hello,

Some hours ago the developer for colors seems to have broken his library. 1.4.0 is still working as it seems, but 1.4.1 and 1.4.2 contain an OOM!!

Your current dep 

https://github.com/flatiron/prompt/blob/master/package.json#L22

will get this version and so break all updated systems!!

Please consider pinning it to 1.4.0 or (maybe second stept) replace it by something else (maybe chalk)

This would be urgent because it now starts to break all projects that use your library (3.360 according to npm right now).

Than k you for a fast reaction on this topic!

**Comment by Apollon77** [comment]
see https://github.com/flatiron/prompt/pull/219

**Comment by caub** [comment]
ok will do now

**Comment by Apollon77** [comment]
Thank you very much for your fast reaction
