### ISSUE TITLE
cursor position error with multibyte string descriptions

### ISSUE THREAD

**Issue by danielking** [flatiron/prompt#50]
schema:
```coffee-script
schema =
	properties:
		'username':
			description: '用户名'
			pattern: /^[a-zA-Z\s\-]+$/
			message: '用户名必须由字母、空格、横线组成'
			required: true
		'password':
			description: '密码'
			required: true
			hidden: true
```
result:
```
prompt: 用户名d
prompt: 密码:
{ username: 'd', password: 'a' }
```

and i have another question:
How to remove the prefix of each line such as "prompt: " "error: ". or place them with other strings
```
提示: 
错误: 
...
```

**Comment by gangstead** [comment]
Fixed in latest versions of node:
![image](https://cloud.githubusercontent.com/assets/527760/12822057/d2e971bc-cb2b-11e5-99ad-7714c23e6cc9.png)

The second question is fixed as of #61 by disabling prompt.message.
