### ISSUE TITLE
Chinese characters problem

### ISSUE THREAD

**Issue by hiwanz** [flatiron/prompt#78]
var prompt = require('prompt');
prompt.start();

prompt.get(['中文'], function (err, result) {
	console.log('  username: ' + result['中文']);
});

this works fine itself.
![1](https://f.cloud.github.com/assets/338102/1703113/1f3909b4-60ae-11e3-983d-98ecc03829d2.jpg)

but when i use this snippet in my project,it comes across problem below:
![2](https://f.cloud.github.com/assets/338102/1703116/263cac7a-60ae-11e3-9440-71112ca48288.jpg)

the cursor goes in wrong position :(

**Comment by gangstead** [comment]
Not sure if actual mistake, but it's been 2 years so I'm closing this.  Please reopen if you can add more context.
