### ISSUE TITLE
[feature request] return a promise from prompt.get()

### ISSUE THREAD

**Issue by jblashill** [flatiron/prompt#81]
I've found that wrapping prompt() in a method that returns a promise has lead to cleaner and more maintainable code. That is, I do something like this:

```javascript
var promptUser = function(schema) {
  return new Promise(resolve, reject) {
    prompt.get(schema, function(err, result) {
      if (err) {
        reject(err);
      } else {
        resolve(result);
      }
    });
  };
};
```

This allows me to write expressive code like (omitting function details):

```javascript
promptUser(["name", "email", "password"])
  .then(addUserToDb)
  .then(sendUserEmail)
  .then(printUser)
  .catch(printError);
```

It would be great if rather than using the callback in prompt.get() if you could also return a promise as well. It's a minor thing since it's so easy to wrap the call but I think it's worthwhile to promote.

FYI, the promises API used above is this polyfill for the ES6 Promises API: https://github.com/jakearchibald/es6-promise

Thanks for the consideration!

**Comment by jfrumar** [comment]
:+1:

**Comment by jcrugzz** [comment]
@jblashill unfortunately adding more abstraction to this module will not happen (we are personally not fans of promises here sorry). I'd recommend writing a wrapper module to wrap prompt to return promises to help out anyone else who also enjoys the same abstraction.

**Comment by jblashill** [comment]
hey, no worries. thanks for responding.

incidently, if I were to do this today I'd write an async function anyway so my above usage example would look more like:

```
let [user,name,password] = await promptUser(['name', 'email', 'password']);
// ect..
```

**Comment by jcrugzz** [comment]
@jblashill seems like you can get something like this sometime soon using [`babel`](https://github.com/babel/babel). And no problem :)

**Comment by marcoscaceres** [comment]
be great to reconsider this issue. I've also been using it with promises + asycn/await like pattern. It makes code much cleaner. E.g., 

https://github.com/w3c/respec/blob/develop/tools/release.js
