### ISSUE TITLE
Is it possible to use prompt in a script that gets executed by another script?

### ISSUE THREAD

**Issue by heff** [flatiron/prompt#82]
I'm working on a CLI that at a certain point executes a grunt task, and the grunt task includes prompt. In this case, prompt hangs after you respond to the prompt.

The reduced test case looks like:

cli-with-prompt.js - The script that uses prompt
```js
#!/usr/bin/env node

var prompt = require('prompt');
prompt.start();
prompt.get([{
  name: 'test',
  required: true
}], function (err, result) {
  console.log(err, result);
  console.log('done!');
});
```

cli.js - The script that executes the previous script
```js
#!/usr/bin/env node

var shell = require('shelljs');
shell.exec('node cli-with-prompt.js');
```

cli-with-prompt.js works
```bash
~/Code/prompt-test $ node cli-with-prompt.js 
prompt: test:  hi
null { test: 'hi' }
done!
```

cli.js hangs
```bash
~/Code/prompt-test $ node cli.js
prompt: test:  hi

```
(hangs)

Is there any way to make this type of setup possible, or threads to follow?

**Comment by gangstead** [comment]
Looking at the docs for [shelljs exec](https://github.com/shelljs/shelljs#execcommand--options--callback) it looks like you either need to provide a callback or pass in `{async:true}`.

**Comment by gangstead** [comment]
I'm sure you haven't been waiting around 2 years for this response so I'm going to assume you've moved on and provisionally close this issue, but if you get a chance to verify or want to add more info we'll open it back up.

**Comment by heff** [comment]
Awesome, thanks for the response! :) The project I was working on was [contrib](https://github.com/contrib/contrib). I still use it and this may still be relevant, so I'll make a note.

**Comment by jackyon** [comment]
hi @heff, did you found the solution? I am also confuse about this. plz advise.

**Comment by heff** [comment]
No, sorry. It’s been a while since I’ve thought about this.
