### ISSUE TITLE
If "required" is set to true, in properties, all prompt messages appears twice 

### ISSUE THREAD

**Issue by NidhiArien** [flatiron/prompt#94]
I am using prompt in expressjs version4. I tried the include the following example in my code:

=====================================================
 var schema = {
    properties: {
      name: {
        pattern: /^[a-zA-Z\s\-]+$/,
        message: 'Name must be only letters, spaces, or dashes',
        required: true
      },
      password: {
        hidden: true
      }
    }
  };

  //
  // Start the prompt
  //
  prompt.start();

  //
  // Get two properties from the user: email, password
  //
  prompt.get(schema, function (err, result) {
    //
    // Log the results.
    //
    console.log('Command-line input received:');
    console.log('  name: ' + result.name);
    console.log('  password: ' + result.password);
  });

================================================

So if I do not enter the name in the first try, I get the below prompts:
===================================================
prompt: name:  

error:   Invalid input for name
error:   Name must be only letters, spaces, or dashes
prompt: name:
error:   Invalid input for name
error:   Name must be only letters, spaces, or dashes
prompt: name:

==============================================
Why are my prompt error messages appearing twice?

**Comment by cascornelissen** [comment]
:+1:, I'm running into the exact same problem.

**Comment by gangstead** [comment]
What platform are you on?  There are some other terminal output related issues reported that are Linux.  If so I'll have to dig up a Linux computer to trouble shoot on.

**Comment by cascornelissen** [comment]
I am (was) on Windows 10, running Cmder

**Comment by gangstead** [comment]
Thanks for the update.  I tried your code and am only seeing it once, but I'm on a mac.

**Comment by gangstead** [comment]
Any chance you can try on Node v5?  In #131 it appears that a Windows specific bug is going away between Node 4.2.X and Node 5.X.X

**Comment by cascornelissen** [comment]
I'm running Node 5.1.1 and it indeed seems to be fixed for me.

**Comment by gangstead** [comment]
I'm going to go ahead and close since we have a fix (Windows users upgrade to Node 5).  It doesn't give me warm feelings that the root cause wasn't found, but at least we have an answer for anyone else with the problem.  If anybody disagrees anyone can always reopen.
