### ISSUE TITLE
process.stdin

### ISSUE THREAD

**Issue by jamieGee** [flatiron/prompt#95]
prompt.start uses process.stdin if no stdin property is passed on the options (lib/prompt.js line 74), however some environments don't have process.stdin. I've run into this problem using IISNODE on Microsoft Azure. Worked around it by adding '|| {}' to the end of this line but perhaps it should check for the existence of process.stdin?

**Comment by gangstead** [comment]
Closing out stale issues.  This is a great feature request but in the mean time it sounds like you have a work around.
